spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      idle-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

server:
  port: ${APP_PORT:8080}

logging:
  level:
    com.part2.monew: DEBUG

monew:
  batch:
    news-collection:
      enabled: ${BATCH_NEWS_COLLECTION_ENABLED:true}
      backup:
        enabled: ${BATCH_BACKUP_ENABLED:true}
      s3-upload:
        enabled: ${BATCH_S3_UPLOAD_ENABLED:true}
